### ISSUE TITLE
decorator not working with autoDI

### ISSUE THREAD

**Issue by dakorpar** [fmasa/auto-di#3]
Consider this:
```
decorator:
    App\Repositories\BaseRepository:
        inject: on
```
```
autoDI:
    services:
        - class: App\Repositories\*Repository
```
inject functions are not called when using autoDI but works perfectly when registered manually.

**Comment by dakorpar** [comment]
This works so it's kinda ok, although decorator should work with this, otherwise sometimes you'll have to repeat the same through multiple folders 
```
autoDI:
    services:
        - class: App\Repositories\*Repository
          inject: on
```
